export const MEME_QUOTES = {
  "Drake-Hotline-Bling": [
    ["Paying for no-ad streaming", "Watching it on a sketchy site 2 mins later"],
    ["Reading the documentation", "Trial and error until it works"],
    ["Speaking to a human", "Pressing '0' repeatedly"],
    ["8 hours of sleep", "Revenge bedtime procrastination"],
    ["Detailed Jira tickets", " 'Fixing stuff'"],
    ["Eating a salad", "Girl dinner"],
    ["Replying to texts", "Mental telepathy"],
    ["New Year's resolutions", "The same me, just tired"],
    ["Hiring a professional", "YouTube tutorial at 2 AM"],
    ["Acknowledging burnout", "Just one more coffee"],
  ],
  "Distracted-Boyfriend": [
    ["My unfinished tasks", "Me", "A new side project"],
    ["Healthy coping mechanisms", "Me", "Doomscrolling"],
    ["My actual job", "Me", "Googling 'how to start a goat farm'"],
    ["The 50 tabs I have open", "Me", "Opening a new tab"],
    ["Water", "Me", "Iced coffee"],
    ["Sleep", "Me", "Video essays on lore of a game I don't play"],
    ["Saving money", "Me", "Little treat culture"],
    ["Logic", "Me", "Delusion"],
  ],
  "Two-Buttons": [
    ["Save money", "Buy aesthetic desk setup"],
    ["Be mysterious", "Overshare on main"],
    ["Go to bed", "Watch one more short"],
    ["Confront the issue", "Ghost everyone"],
    ["Cook dinner", "Order $40 delivery"],
    ["Start the assignment", "Clean the entire house"],
    ["Ask for help", "Suffer in silence"],
    ["Be productive", "Rot in bed"],
  ],
  "Success-Kid": [
    ["Woke up", "Didn't choose violence"],
    ["Plugged in USB", "First try"],
    ["Meeting could've been an email", "It WAS an email"],
    ["Forgot password", "Guessed it right"],
    ["Dropped phone", "Screen didn't crack"],
    ["Sent risky text", "They matched the energy"],
    ["Checking bank account", "More money than expected"],
    [" Cancelled plans", "They cancelled first"],
    ["Online order", "Arrived early"],
    ["Code compiled", "No errors"],
  ],
  "One-Does-Not-Simply": [
    ["One does not simply", "Watch just one TikTok"],
    ["One does not simply", "Unsubscribe from emails"],
    ["One does not simply", "Leave Target empty handed"],
    ["One does not simply", "Plug a USB in correctly"],
    ["One does not simply", "Remember a password"],
    ["One does not simply", "Drive in silence"],
    ["One does not simply", "Ignore a notification"],
    ["One does not simply", "Explain the lore"],
  ],
  "Change-My-Mind": [
    ["Coffee is just bean soup", "Change my mind"],
    ["Hot dogs are tacos", "Change my mind"],
    ["Cereal is soup", "Change my mind"],
    ["The book was better", "Change my mind"],
    ["Pineapple belongs on pizza", "Change my mind"],
    ["Clicking tongs twice is mandatory", "Change my mind"],
    ["Fonts have personalities", "Change my mind"],
    ["Dark mode is the only mode", "Change my mind"],
  ],
  "generic": [
    ["Me functioning", "On 1% battery"],
    ["My brain during an exam:", "Songs from 2012"],
    ["Nobody:", "Me at 3 AM:"],
    ["Therapist: And what do we say?", "Me: It is what it is"],
    ["My toxic trait:", "Thinking I can do it in one trip"],
    ["Adulting is just", "Googling how to do stuff"],
    ["I don't need sleep", "I need answers"],
    ["Vibe check:", "Chaotic good"],
    ["Current status:", "Holding it together with duct tape"],
    ["My patience level:", "Loading..."],
    ["Me:", " *screams internally* "],
    ["When the WiFi drops", "And you have to face reality"],
    ["Pov:", "You're the main character"],
    ["Emotional damage", "100%"],
    ["Send memes", "Not texts"],
    ["I'm not ignoring you", "I'm just overwhelmed by existence"],
    ["Trying to act normal", "Failing miserably"],
    ["Brain:", "Let's replay every cringe moment"],
    ["Money can't buy happiness", "But it can buy snacks"],
    ["Born to sleep", "Forced to work"],
    ["Error 404:", "Motivation not found"],
    ["Me looking at my code:", "Who wrote this trash?"],
    ["Also me:", "Oh wait, I did"],
    ["Me asking for advice", "Then doing the exact opposite"],
    ["My two moods:", "Sleepy / Stressed"],
    ["Everything is fine", " *fire burning in background* "],
    ["When you realize", "It's only Tuesday"],
    ["Main character energy", "Background character budget"],
    ["Very demure", "Very mindful"],
    ["Bombastic side eye", "Criminal offensive side eye"],
    ["I am you", "But stronger"],
    ["Just here for", "The plot"],
    ["Not all heroes wear capes", "Some just hold the camera"],
    ["When life gives you lemons", "Make a meme about it"],
    ["Mood:", "Unbothered"],
    ["Living my best life", "In my head"],
    ["This is fine", "I'm okay with the events that are unfolding"],
    ["Why is everything", "So expensive?"],
    ["Don't talk to me", "I haven't had my coffee"],
    ["My social battery", "Is critically low"],
    ["I promise I'm listening", "I'm just disassociating"],
    ["Reality called", "I hung up"],
    ["Running on caffeine", "And anxiety"],
    ["If lost,", "Return to bed"],
    ["Do I need it?", "No. Will I buy it? Yes."],
    ["Me trying to budget:", " *buys iced coffee* "],
    ["Sorry I'm late", "I didn't want to come"],
    ["I wish I could", "But I don't want to"],
    ["My spirit animal", "Is a raccoon"],
    ["Chaos", "Is my love language"]
  ]
};
