export const MEME_QUOTES = {
  "Drake-Hotline-Bling": [
    ["Going to bed early", "Watching 'How it's made' at 3 AM"],
    ["Eating healthy", "McDonald's at midnight"],
    ["Taking the stairs", "Waiting 5 min for an elevator"],
    ["Saving money", "Just one more thing from Amazon"],
    ["Doing laundry", "The floor is an outfit option"],
    ["Cooking at home", "Ordering DoorDash again"],
    ["Finishing the to-do list", "Starting a new hobby"],
    ["Texting back immediately", "Leaving them on read for 3 days"],
    ["8 hours of sleep", "2 hours + existential dread"],
    ["Regular coffee", "Triple shot espresso with chaos"],
  ],
  "Distracted-Boyfriend": [
    ["New phone", "Me", "Phone I bought last year"],
    ["Side Project", "Me", "Sleep"],
    ["New restaurant", "Me", "The same 5 places I always go"],
    ["McDonald's", "Me", "Eating healthy"],
    ["Procrastination", "Everyone", "Actual responsibilities"],
    ["Weekend plans", "Me", "My couch"],
    ["A new hobby", "Me", "The 12 hobbies I already started"],
    ["The gym", "January Me", "February Me's excuses"],
  ],
  "Two-Buttons": [
    ["Watch one episode", "Binge entire season"],
    ["Start working", "One more video"],
    ["Buy it now", "Think about it for 3 months"],
    ["Wake up early", "5 more minutes"],
    ["Be productive", "Take a nap"],
    ["Save the leftovers", "Eat everything now"],
    ["Ask for directions", "Drive around lost for an hour"],
    ["Read the manual", "Figure it out myself"],
  ],
  "Success-Kid": [
    ["Found a dollar", "In my winter coat"],
    ["Pizza arrived", "10 minutes early"],
    ["Woke up early", "Naturally"],
    ["Phone at 1%", "Found the charger"],
    ["Ran to catch the bus", "Driver waited"],
    ["Said something awkward", "Nobody noticed"],
    ["Overslept", "Meeting got canceled"],
    ["Almost dropped my phone", "Caught it mid-air"],
    ["Forgot to study", "Test was postponed"],
    ["Parallel parked", "On the first try"],
  ],
  "One-Does-Not-Simply": [
    ["One does not simply", "Eat just one chip"],
    ["One does not simply", "Walk into Mordor"],
    ["One does not simply", "Stop at one fry"],
    ["One does not simply", "Watch one episode"],
    ["One does not simply", "Leave IKEA in under 3 hours"],
    ["One does not simply", "Ignore the snack aisle"],
    ["One does not simply", "Go to Target for one thing"],
    ["One does not simply", "Skip the intro"],
  ],
  "Change-My-Mind": [
    ["Pineapple belongs on pizza", "Change my mind"],
    ["Hotdogs are sandwiches", "Change my mind"],
    ["Coffee is bean soup", "Change my mind"],
    ["Dark mode is superior", "Change my mind"],
    ["Cereal is a soup", "Change my mind"],
    ["Water is the best drink", "Change my mind"],
    ["Naps are underrated", "Change my mind"],
    ["Socks with sandals is a look", "Change my mind"],
  ],
  "generic": [
    ["Me when", "I find extra fries at the bottom"],
    ["Nobody:", "Absolutely nobody:"],
    ["POV:", "You are looking at a masterpiece"],
    ["I have no idea", "What I am doing"],
    ["The face you make", "When you realize it's Monday"],
    ["Wait,", "That's illegal"],
    ["Am I a joke", "To you?"],
    ["Listen here", "You little..."],
    ["It's giving", "Main character energy"],
    ["Caught in 4K", "No excuses"],
    ["Same energy", "Different font"],
    ["You're not lazy", "You're on energy-saving mode"],
    ["Plot twist:", "Adulthood is a scam"],
    ["Life hack:", "Lower your expectations"],
    ["Current mood:", "Chaotic neutral"],
    ["My brain at 3 AM:", "Let's overthink everything"],
    ["Me pretending to care", "About things I don't care about"],
    ["When I say I'll be ready in 5", "I mean 45 minutes"],
    ["Looking for motivation", "Still looking"],
    ["My plans:", "Reality:"],
    ["The internet", "Is undefeated"],
    ["Today's mood:", "Unbothered but entertained"],
    ["Same,", "Here's a meme to cope"],
    ["When you laugh so hard", "You forget your problems"],
    ["Not all heroes wear capes", "Some just share memes"],
    ["Keep calm", "And meme on"],
    ["When life gives you lemons", "Turn them into a meme"],
    ["This hits harder", "Than Monday morning"],
    ["Why does it", "Always do that?"],
    ["I am", "Already tired"],
    ["Who needs sleep", "When you have anxiety?"],
    ["Me? Over the top?", "I'm just warming up"],
    ["Sass level:", "Expert"],
    ["Touch", "Grass"],
    ["Let them", "Cook"],
    ["It's not", "That deep"],
    ["They don't know", "I'm the main character"],
    ["Be so", "For real right now"],
    ["Ate and left", "No crumbs"],
    ["Real talk:", "I need a vacation"],
    ["This is", "Fine"],
    ["Where", "Banana?"],
    ["They're the same", "Picture"],
    ["This is where I'd put my trophy", "If I had one"],
    ["Always Has", "Been"],
    ["We are", "Not the same"],
    ["Still looking", "For a reason"],
    ["Hide the Pain", "Harold energy"],
    ["I Bet He's Thinking About", "Food again"],
    ["Surprised", "Pikachu face"],
    ["Evil version:", "Approves"],
    ["Spiderman pointing", "At Spiderman"],
    ["The Scroll", "Of Truth"],
    ["When I'm in a competition", "And my opponent shows up"],
    ["Whisper", "And Goosebumps"],
    ["Clown", "Applying Makeup"],
    ["Woman Yelling", "At Cat"],
    ["Batman Slapping", "Robin"],
    ["My plan:", "Profit somehow"],
    ["Panik", "Kalm", "Panik"],
    ["Sleeping", "Shaq"],
    ["Me explaining", "Why I deserve a treat"],
    ["Instructions unclear", "Made it worse"],
    ["Task failed", "Successfully"],
    ["I don't always post memes", "But when I do, they're fire"],
    ["Friendship ended", "New bestie acquired"],
    ["Excuse me", "What?"],
    ["How it started", "How it's going"],
    ["Say sike", "Right now"],
    ["Is this", "A personal attack?"],
    ["My last two brain cells", "Working overtime"],
    ["Tell me you're tired", "Without telling me you're tired"],
    ["Nobody asked but", "Here I am anyway"],
    ["Me at the store:", "Only needed milk"],
    ["Expectation:", "Reality:"],
    ["I came here to", "Have a good time"],
    ["When you finally", "Get your life together"],
    ["Normal people:", "Me:"],
    ["5 minutes into Netflix", "And chill"],
    ["Record scratch", "Freeze frame"],
    ["Therapist:", "And how does that make you feel?"],
    ["First day vs", "3 months later"],
    ["2024:", "2025:"],
    ["Before coffee:", "After coffee:"],
    ["The duality", "Of man"],
    ["What I ordered", "What I got"],
    ["Mood forever:", "Unbothered king/queen"],
    ["Remember when", "Good times"],
    ["If I had a dollar for every time", "I'd be rich"],
    ["That one friend", "Who always says that"],
    ["Local man ruins", "Everything"],
    ["Breaking news:", "Water is wet"],
    ["Scientists confirm:", "The floor is made of floor"],
    ["New fear:", "Unlocked"],
    ["POV:", "You just saw something cursed"],
    ["Tell me why", "Ain't nothing but a heartache"],
    ["My face when", "Someone eats my food"],
    ["The audacity", "Of some people"],
    ["When the WiFi goes out", "For 2 seconds"],
    ["Inner peace:", "Achieved for 5 seconds"],
    ["This could be us", "But we're both awkward"],
    ["Not me reading this", "At 2 AM"]
  ]
};
