export const MEME_QUOTES = {
  "Drake-Hotline-Bling": [
    ["Paying for no-ad streaming", "Watching it on a sketchy site 2 mins later"],
    ["Reading the documentation", "Trial and error until it works"],
    ["Speaking to a human", "Pressing '0' repeatedly"],
    ["8 hours of sleep", "Revenge bedtime procrastination"],
    ["Detailed Jira tickets", " 'Fixing stuff'"],
    ["Eating a salad", "Girl dinner"],
    ["Replying to texts", "Mental telepathy"],
    ["New Year's resolutions", "The same me, just tired"],
    ["Hiring a professional", "YouTube tutorial at 2 AM"],
    ["Acknowledging burnout", "Just one more coffee"],
    ["Going to therapy", "Making memes about it"],
    ["Having a savings account", "Treating myself because I deserve it"],
    ["Leaving on read", "Triple texting at 2 AM"],
    ["Dating app bios", "Judging by Spotify wrapped"],
    ["Gym membership", "Mental breakdowns in my car"],
  ],
  "Distracted-Boyfriend": [
    ["My unfinished tasks", "Me", "A new side project"],
    ["Healthy coping mechanisms", "Me", "Doomscrolling"],
    ["My actual job", "Me", "Googling 'how to start a goat farm'"],
    ["The 50 tabs I have open", "Me", "Opening a new tab"],
    ["Water", "Me", "Iced coffee"],
    ["Sleep", "Me", "Video essays on lore of a game I don't play"],
    ["Saving money", "Me", "Little treat culture"],
    ["Logic", "Me", "Delusion"],
    ["My responsibilities", "Me", "A new hobby I'll abandon in 2 weeks"],
    ["The gym", "Me", "My couch"],
    ["Healthy food", "Me", "Late night snacks"],
    ["Work emails", "Me", "Literally anything else"],
  ],
  "three-tier-variety": [
    // Story format: Setup / Action / Result
    ["Step 1: Open Wikipedia", "Step 2: Click one link", "Step 47: How dolphins sleep"],
    ["Alarm: 7 AM", "Snooze: 7:09 AM", "Panic: 7:45 AM"],
    ["Package shipped", "Out for delivery", "We missed you (lies)"],
    ["Add to cart", "Maybe later", "Why is my wallet empty???"],
    ["Start cooking", "Missing one ingredient", "Ordering pizza"],
    ["Read the recipe once", "Wing it completely", "Smoke detector is the timer"],
    // Role/Character format
    ["How I think I look:", "How my camera sees me:", "How I actually look:"],
    ["What I said:", "What they heard:", "What I meant:"],
    ["My resume:", "The interview:", "The actual job:"],
    ["The trailer:", "The movie:", "The book:"],
    ["The plan:", "The reality:", "The cope:"],
    ["Online:", "In person:", "In my head:"],
    // Before/During/After
    ["Before coffee:", "During coffee:", "After coffee:"],
    ["Monday morning:", "Wednesday:", "Friday 4:59 PM:"],
    ["Start of the semester:", "Midterms:", "Finals week:"],
    ["January 1st:", "January 15th:", "February:"],
    ["New relationship energy:", "3 months in:", "Married 10 years:"],
    ["First day at gym:", "One week later:", "Gym who???"],
    // Comparison format
    ["What teachers think:", "What students do:", "What the syllabus says:"],
    ["Expectation:", "Reality:", "Acceptance:"],
    ["My anxiety:", "The actual problem:", "My solution:"],
    ["The recipe:", "My version:", "The result:"],
    ["Budget:", "Cart total:", "My bank account:"],
    ["What I ordered:", "What I got:", "Still ate it:"],
    // Internet/Meme culture
    ["POV: You're the:", "Main character and:", "The plot thickens"],
    ["Nobody:", "Absolutely nobody:", "Me at 3 AM:"],
    ["Friend 1:", "Friend 2:", "The group chat:"],
    ["The question:", "My brain:", "What I said:"],
    ["Google:", "WebMD:", "My mom:"],
    ["Spotify:", "My playlist:", "My personality:"],
    // Life stages
    ["Childhood dream:", "Adult reality:", "At least I tried:"],
    ["18-year-old me:", "25-year-old me:", "30-year-old me:"],
    ["What I wanted:", "What I got:", "Actually pretty good:"],
    ["Theory:", "Practice:", "Pure chaos:"],
    ["Dating profile:", "First date:", "Third date:"],
    ["Morning me:", "Afternoon me:", "Night owl me:"],
  ],

  "Two-Buttons": [
    ["Save money", "Buy aesthetic desk setup"],
    ["Be mysterious", "Overshare on main"],
    ["Go to bed", "Watch one more short"],
    ["Confront the issue", "Ghost everyone"],
    ["Cook dinner", "Order $40 delivery"],
    ["Start the assignment", "Clean the entire house"],
    ["Ask for help", "Suffer in silence"],
    ["Be productive", "Rot in bed"],
    ["Reply to emails", "Pretend they don't exist"],
    ["Touch grass", "One more episode"],
    ["Use vacation days", "Flex PTO I'll never take"],
    ["Apologize", "Double down"],
  ],
  "Success-Kid": [
    ["Woke up", "Didn't choose violence"],
    ["Plugged in USB", "First try"],
    ["Meeting could've been an email", "It WAS an email"],
    ["Forgot password", "Guessed it right"],
    ["Dropped phone", "Screen didn't crack"],
    ["Sent risky text", "They matched the energy"],
    ["Checking bank account", "More money than expected"],
    [" Cancelled plans", "They cancelled first"],
    ["Online order", "Arrived early"],
    ["Code compiled", "No errors"],
    ["Wrote the email", "Didn't have to send it"],
    ["Parallel parked", "First attempt"],
    ["Left the house", "Had everything I needed"],
    ["Found my keys", "In the first place I looked"],
  ],
  "One-Does-Not-Simply": [
    ["One does not simply", "Watch just one TikTok"],
    ["One does not simply", "Unsubscribe from emails"],
    ["One does not simply", "Leave Target empty handed"],
    ["One does not simply", "Plug a USB in correctly"],
    ["One does not simply", "Remember a password"],
    ["One does not simply", "Drive in silence"],
    ["One does not simply", "Ignore a notification"],
    ["One does not simply", "Explain the lore"],
    ["One does not simply", "Skip the intro"],
    ["One does not simply", "Have just one snack"],
    ["One does not simply", "Check email once"],
    ["One does not simply", "Leave a store on time"],
  ],
  "Change-My-Mind": [
    ["Coffee is just bean soup", "Change my mind"],
    ["Hot dogs are tacos", "Change my mind"],
    ["Cereal is soup", "Change my mind"],
    ["The book was better", "Change my mind"],
    ["Pineapple belongs on pizza", "Change my mind"],
    ["Clicking tongs twice is mandatory", "Change my mind"],
    ["Fonts have personalities", "Change my mind"],
    ["Dark mode is the only mode", "Change my mind"],
    ["Reply all is a crime", "Change my mind"],
    ["Monday should be optional", "Change my mind"],
    ["Oat milk hits different", "Change my mind"],
    ["Naps are elite", "Change my mind"],
  ],
  "work-life": [
    ["Me in the meeting:", "Muted, camera off, vibing"],
    ["9 to 5?", "More like whenever my laptop opens"],
    ["Corporate wants you to find the difference", "They're the same picture"],
    ["Let me just", "Circle back on that"],
    ["Per my last email:", "Can you read?"],
    ["Working from home:", "Attending meetings in pajamas"],
    ["Quick sync?", "Absolutely not"],
    ["Can't make the meeting", "I have a hard stop"],
    ["Moving forward", "Let's table this"],
    ["Hope this finds you well", "It did not"],
    ["As discussed", "As I already told you 47 times"],
    ["Taking this offline", "I'm done with this conversation"],
    ["Let's unpack this", "I have no idea what you said"],
    ["I'll handle it EOD", "I'll panic at 11:59 PM"],
    ["Quick question", "It's never quick"],
    ["Just following up", "Why haven't you responded?"],
    ["Thoughts?", "Do my job for me please"],
    ["Synergy", "Absolutely nothing"],
    ["Touch base", "Waste your time"],
    ["Deep dive", "Google it"],
  ],
  "dating": [
    ["Height:", "Does it matter if I'm lying down?"],
    ["Looking for:", "Someone to trauma bond with"],
    ["Green flags only", "Still chose red ones"],
    ["Healing my attachment style", "By scrolling dating apps"],
    ["I'm a 10", "On the pH scale (basic)"],
    ["Dating me is like:", "A limited time offer"],
    ["Looking for the one", "But multiple backups"],
    ["What's your love language?", "Unsent messages"],
    ["Ready for commitment", "To a streaming service"],
    ["My type:", "Emotionally unavailable"],
    ["First date energy:", "Job interview vibes"],
    ["Let's do something spontaneous", "That I've planned for 3 weeks"],
    ["I'm looking for a connection", "WiFi is acceptable"],
    ["Swipe right if:", "You've touched grass recently"],
    ["Not looking for hookups", "*matches with profile that says hookups only*"],
  ],
  "social-media": [
    ["The algorithm:", "Shows me my exact trauma"],
    ["Going viral:", "For something embarrassing"],
    ["Just one more scroll", "*3 hours later*"],
    ["Posted and deleted", "Core memory created"],
    ["Ratio", "Devastating"],
    ["Main character energy", "Extra budget"],
    ["The vibe is:", "Immaculate"],
    ["This song lives in my head", "Rent free"],
    ["Chronically online", "It's a lifestyle"],
    ["Touch grass?", "The WiFi out there is terrible"],
    ["Real and true", "Factual"],
    ["No notes", "Pure perfection"],
    ["That's so sigma", "Or is it skibidi?"],
    ["Fr fr", "No cap"],
    ["It's giving:", "Everything it needs to give"],
    ["Slay", "Consumed"],
    ["Mother is mothering", "The children are thriving"],
    ["Ate and left no crumbs", "Cleaned the plate"],
    ["Understood the assignment", "Extra credit"],
    ["The serve", "Is being served"],
  ],
  "gaming": [
    ["One more game", "Said 7 games ago"],
    ["I'm not addicted", "I can stop anytime"],
    ["GG EZ", "After being carried"],
    ["Lag killed me", "Definitely not skill issue"],
    ["Trust the process", "Process has failed"],
    ["Main quest:", "Side quests first though"],
    ["Tutorial complete", "Real suffering begins"],
    ["Save point:", "Time to do something stupid"],
    ["Inventory full", "I might need all of it"],
    ["Speedrun any%", "My mental stability"],
    ["Rage quit?", "Strategic retreat"],
    ["Gaming setup:", "$3000. Chair:", "$30"],
    ["My sleep schedule:", "Respawning at noon"],
    ["Pay to win?", "Pay to suffer stylishly"],
    ["The grind never stops", "Neither does my back pain"],
  ],
  "finance": [
    ["Checking my bank account", "Immediate regret"],
    ["Treat yourself", "Bankruptcy"],
    ["Budgeting:", "Ignoring reality stylishly"],
    ["Investing in my future", "By buying coffee instead"],
    ["Passive income:", "Aggressively zero"],
    ["Should I buy it?", "Already bought it"],
    ["Savings goals:", "Existing"],
    ["Crypto expert:", "*down 80%*"],
    ["Financial advice:", "Don't ask me"],
    ["Side hustle:", "My main hustle's broke"],
    ["Rich auntie energy", "Poor nephew reality"],
    ["Money can't buy happiness", "But it can buy snacks"],
    ["Splurging responsibly", "Oxymoron achieved"],
    ["Emergency fund:", "Emotional emergencies count"],
    ["Living paycheck to paycheck", "At least it's consistent"],
  ],
  "mental-health": [
    ["Me practicing self-care:", "Rotting in bed"],
    ["Therapy:", "Paying to explain the lore"],
    ["Healing journey:", "Plot twist: more trauma"],
    ["Boundaries:", "Still learning the concept"],
    ["Growth mindset:", "Crying differently now"],
    ["Affirmations:", "I am not okay and that's okay"],
    ["Work-life balance:", "Both are unbalanced"],
    ["Journal prompt:", "Existential crisis time"],
    ["Mindfulness:", "Mind full of nonsense"],
    ["Inner peace:", "Page not found"],
    ["Self-care Sunday:", "Every day is a struggle day"],
    ["Hot girl walk:", "Anxious girl sit"],
    ["Romanticizing life:", "Dissociating aesthetically"],
    ["Wellness routine:", "Surviving"],
    ["Shadow work:", "Meeting my toxic traits"],
  ],
  "pop-culture": [
    ["It's giving:", "It gave"],
    ["The vibes are:", "Off"],
    ["Very demure", "Very mindful"],
    ["Bombastic side eye", "Criminal offensive side eye"],
    ["I fear", "No explanation needed"],
    ["Not me", "Absolutely me"],
    ["Real", "Factual"],
    ["No because", "Absolutely yes"],
    ["Brain rot complete", "Achievement unlocked"],
    ["Core memory:", "Unlocked"],
    ["Hyperfixation:", "New personality acquired"],
    ["Rent free", "In my head permanently"],
    ["Ate that", "Left no crumbs"],
    ["Understood the assignment", "Got extra credit"],
    ["Standards:", "In the trenches"],
    ["Delulu is the solulu", "Living in fantasy"],
    ["It's chewsday innit", "British meme activated"],
    ["Okay I pull up", "Capybara energy"],
    ["Skibidi", "Ohio sigma moment"],
    ["Grimace shake survived:", "Main character arc complete"],
  ],
  "generic": [
    ["Me functioning", "On 1% battery"],
    ["My brain during an exam:", "Songs from 2012"],
    ["Nobody:", "Me at 3 AM:"],
    ["Therapist: And what do we say?", "Me: It is what it is"],
    ["My toxic trait:", "Thinking I can do it in one trip"],
    ["Adulting is just", "Googling how to do stuff"],
    ["I don't need sleep", "I need answers"],
    ["Vibe check:", "Chaotic good"],
    ["Current status:", "Holding it together with duct tape"],
    ["My patience level:", "Loading..."],
    ["Me:", " *screams internally* "],
    ["When the WiFi drops", "And you have to face reality"],
    ["Pov:", "You're the main character"],
    ["Emotional damage", "100%"],
    ["Send memes", "Not texts"],
    ["I'm not ignoring you", "I'm just overwhelmed by existence"],
    ["Trying to act normal", "Failing miserably"],
    ["Brain:", "Let's replay every cringe moment"],
    ["Money can't buy happiness", "But it can buy snacks"],
    ["Born to sleep", "Forced to work"],
    ["Error 404:", "Motivation not found"],
    ["Me looking at my code:", "Who wrote this trash?"],
    ["Also me:", "Oh wait, I did"],
    ["Me asking for advice", "Then doing the exact opposite"],
    ["My two moods:", "Sleepy / Stressed"],
    ["Everything is fine", " *fire burning in background* "],
    ["When you realize", "It's only Tuesday"],
    ["Main character energy", "Background character budget"],
    ["Very demure", "Very mindful"],
    ["Bombastic side eye", "Criminal offensive side eye"],
    ["I am you", "But stronger"],
    ["Just here for", "The plot"],
    ["Not all heroes wear capes", "Some just hold the camera"],
    ["When life gives you lemons", "Make a meme about it"],
    ["Mood:", "Unbothered"],
    ["Living my best life", "In my head"],
    ["This is fine", "I'm okay with the events that are unfolding"],
    ["Why is everything", "So expensive?"],
    ["Don't talk to me", "I haven't had my coffee"],
    ["My social battery", "Is critically low"],
    ["I promise I'm listening", "I'm just disassociating"],
    ["Reality called", "I hung up"],
    ["Running on caffeine", "And anxiety"],
    ["If lost,", "Return to bed"],
    ["Do I need it?", "No. Will I buy it? Yes."],
    ["Me trying to budget:", " *buys iced coffee* "],
    ["Sorry I'm late", "I didn't want to come"],
    ["I wish I could", "But I don't want to"],
    ["My spirit animal", "Is a raccoon"],
    ["Chaos", "Is my love language"],
    ["Plot twist:", "There was no plot"],
    ["Expectation:", "Reality crashed"],
    ["Professional overthinker", "Amateur coper"],
    ["Hindsight is 20/20", "But I still didn't see that coming"],
    ["Bold of you to assume", "I have a plan"],
  ]
};
