/**
 * Tone Bank — curated caption sets indexed by emotional tone.
 * Used by the "Vibe Shift" AI feature to cycle captions through
 * different vibes without any external API.
 *
 * Each tone maps to a flat array of caption arrays [top, bottom, ...].
 */

export const TONE_NAMES = ["sarcastic", "wholesome", "dramatic", "genz", "formal"];

export const TONE_LABELS = {
  sarcastic: "Sarcastic",
  wholesome: "Wholesome",
  dramatic:  "Dramatic",
  genz:      "Gen-Z",
  formal:    "Formal",
};

export const TONE_BANK = {
  sarcastic: [
    ["Oh great, another Monday", "Said nobody ever"],
    ["My motivation:", "Has left the chat"],
    ["Sure, I'd love to help", "I lied"],
    ["Working hard", "Or hardly working? Yes."],
    ["I'm not lazy", "I'm on energy-saving mode"],
    ["I'm fine", "Everything is fine *eye twitch*"],
    ["Thanks for the feedback", "I'll file it under 'ignore'"],
    ["Let me just", "Pretend I care"],
    ["Wow, what a surprise", "I'm not surprised at all"],
    ["My face when people say", "'Just be positive'"],
    ["Oh you're an expert?", "Please, enlighten me"],
    ["I'm not arguing", "I'm just explaining why I'm right"],
    ["I woke up like this", "Tired and annoyed"],
    ["Best day ever", "Lies I tell myself"],
    ["Another meeting?", "My favorite waste of time"],
    ["Adulting level:", "Microwaving yesterday's coffee"],
    ["My plans vs reality:", "Reality won. Again."],
    ["Tell me more", "I wasn't listening anyway"],
    ["Productivity today:", "Error 404"],
    ["Optimism?", "Never heard of her"],
  ],

  wholesome: [
    ["You're doing great", "And I'm proud of you"],
    ["Small steps", "Still count as progress"],
    ["Be kind to yourself", "You deserve it"],
    ["Today's reminder:", "You matter"],
    ["You don't have to be perfect", "Just be you"],
    ["Sending virtual hugs", "Because you need one"],
    ["It's okay to rest", "Your worth isn't your productivity"],
    ["You made it through today", "That's enough"],
    ["Your best is enough", "Always has been"],
    ["Believe in yourself", "The way your dog believes in you"],
    ["Good things are coming", "Be patient with yourself"],
    ["You're someone's reason", "To smile today"],
    ["Rough day?", "Tomorrow is a fresh start"],
    ["Kindness is free", "Sprinkle it everywhere"],
    ["You're not behind", "You're on your own timeline"],
    ["Take a deep breath", "You've got this"],
    ["Progress isn't linear", "And that's okay"],
    ["Your feelings are valid", "All of them"],
    ["One day at a time", "You're doing amazing"],
    ["The world is better", "Because you're in it"],
  ],

  dramatic: [
    ["IN THIS ECONOMY?!", "The audacity."],
    ["I trusted you", "And you chose chaos"],
    ["The betrayal...", "I will never recover"],
    ["My last brain cell", "Fighting for survival"],
    ["BREAKING NEWS:", "Everything is on fire"],
    ["The prophecy was true", "We were doomed from the start"],
    ["Witness me", "In my final form"],
    ["This is the end", "Of my patience"],
    ["History will remember", "This moment of chaos"],
    ["I didn't choose the chaos life", "The chaos life chose me"],
    ["And on that day", "Humanity knew... it was over"],
    ["THE HORROR", "The absolute horror"],
    ["From the ashes", "We shall rise... maybe tomorrow"],
    ["My villain origin story", "Starts now"],
    ["It was at this moment", "They knew they messed up"],
    ["A tragedy in two acts:", "Hope, then reality"],
    ["The end is nigh", "Or it's just Monday"],
    ["HEAR ME, WORLD", "I am mildly inconvenienced"],
    ["Epic battle:", "Me vs. my responsibilities"],
    ["And so it begins...", "The unraveling"],
  ],

  genz: [
    ["no cap", "this is bussin fr fr"],
    ["it's giving:", "main character energy"],
    ["me when the", "vibes are immaculate"],
    ["slay", "ate and left no crumbs"],
    ["understood the assignment", "extra credit ong"],
    ["lowkey", "this hits different"],
    ["rent free", "in my head permanently"],
    ["the delulu", "is the solulu"],
    ["pov:", "you're that girl"],
    ["not me", "being unhinged again"],
    ["brain rot activated", "skibidi mode on"],
    ["very demure", "very mindful"],
    ["it's the", "audacity for me"],
    ["bestie", "we need to talk"],
    ["caught in 4k", "no explanation needed"],
    ["this is a", "core memory"],
    ["living my", "roman empire era"],
    ["that's so", "sigma coded"],
    ["tell me why", "this is so real"],
    ["ratio + L", "stay pressed"],
  ],

  formal: [
    ["Per my previous observation,", "This is suboptimal."],
    ["I regret to inform you", "That this is unacceptable"],
    ["As per the data,", "We are, in fact, losing"],
    ["Upon further review,", "The situation remains dire"],
    ["Please find attached:", "My resignation from caring"],
    ["With all due respect,", "This is a disaster"],
    ["I would like to formally", "Express my disappointment"],
    ["In accordance with protocol,", "We are doomed"],
    ["For the record:", "I predicted this outcome"],
    ["Respectfully,", "Absolutely not"],
    ["Moving forward,", "Let us pretend this didn't happen"],
    ["To whom it may concern:", "This is a mess"],
    ["Pursuant to our discussion,", "Nothing has improved"],
    ["I trust this email", "Finds you in chaos"],
    ["Kind regards,", "From someone who is not kind right now"],
    ["In conclusion,", "We have concluded nothing"],
    ["The committee has decided:", "That nobody knows what they're doing"],
    ["As previously stated,", "I was right all along"],
    ["Effective immediately,", "I am overwhelmed"],
    ["Please advise.", "Or don't. I've given up."],
  ],
};
